# dataset related
datasource: "../sdf_dataset"
split: "examples/splits/sv2_planes_train.json"

# model options
resnet: "resnet18"
projection_dim: 128
momentum: 0.99 # used in moco and byol only
queue_size: 8192 # used in moco only
pretrained: True

# train options
framework: "simclr"
batch_size: 256
epochs: 200

# loss options
lr: 1.0e-3
lr_schedule: [120, 160] # when to drop lr by 10x
cos_lr: False # whether to use cosine lr schedule
weight_decay: 1.0e-4
temperature: 0.07 # used in simclr and moco only

# logging options
save_every: 50 # save a checkpoint every this number of epochs